#server.port=8090
#server.servlet.context-path=/
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/springweb?serverTimezone=UTC&useSSL=false&useUniCode=yes&characterEncoding=UTF-8
#spring.datasource.username=ssafy
#spring.datasource.password=ssafy
#mybatis.config-location=classpath:/mybatis/mybatisConfig.xml

server:
  port: 8090
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssafy_project1?serverTimezone=UTC&useSSL=false&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    dbcp2:
      max-idle: 20
  servlet:
    multipart:
      max-file-size: 2000
  mail:
    host: smtp.gmail.com
    port: 587
    username: sunghana92@gmail.com
    password: 92tjddnjs93iu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: messages/message           

mybatis:
  config-location: classpath:/mybatis/mybatisConfig.xml

